### ISSUE TITLE
Feature request: option to auto-convert BigNumber responses

### ISSUE THREAD

**Issue by samajammin** [abunsen/etherflow#6]
Hey folks - awesome tool! Love this as a way to test out methods & view example code.

I think a neat feature would be an option to automatically convert BigNumber return values.

e.g. when using your demo site w/ Ethers.js, I sent a request to `eth_getBalance`:
![Image 2020-11-18 at 12 46 02 PM](https://user-images.githubusercontent.com/8097623/99586275-5a351f80-299c-11eb-8490-14eb9802b4c6.png)

It'd be great if there was e.g. a checkbox next to "Send Request to Node" to convert the hex value response to a human readable string (e.g. using Ethers.js's BigNumber parsing: https://docs.ethers.io/v5/api/utils/bignumber/) & to print that result to the console. This would be handy as a quick spot-check for e.g. `eth_gasPrice ` or `eth_getBalance`.

**Comment by abunsen** [comment]
Excellent suggestion! We will definitely add this as a feature.

**Comment by abunsen** [comment]
Added! Thanks for filing the issue!
